apiVersion: v1
kind: Service
metadata:
 
  labels:
    app: game
  name: game
  namespace: default
  
spec:
  allocateLoadBalancerNodePorts: true
  
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: game
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: ae6ed58e18df64ca399565f66dcf33ac-1983197439.us-west-2.elb.amazonaws.com
